/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedGuildIndexRouteImport } from './routes/_protected/guild/index'
import { Route as ProtectedGuildCreateRouteImport } from './routes/_protected/guild/create'
import { Route as ProtectedGuildBrowseRouteImport } from './routes/_protected/guild/browse'
import { Route as ProtectedGuildGuildIdIndexRouteImport } from './routes/_protected/guild/$guildId/index'
import { Route as ProtectedGuildGuildIdApplicationsRouteImport } from './routes/_protected/guild/$guildId/applications'
import { Route as ProtectedGuildGuildIdMembersUserIdRouteImport } from './routes/_protected/guild/$guildId/members/$userId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGuildIndexRoute = ProtectedGuildIndexRouteImport.update({
  id: '/guild/',
  path: '/guild/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGuildCreateRoute = ProtectedGuildCreateRouteImport.update({
  id: '/guild/create',
  path: '/guild/create',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGuildBrowseRoute = ProtectedGuildBrowseRouteImport.update({
  id: '/guild/browse',
  path: '/guild/browse',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGuildGuildIdIndexRoute =
  ProtectedGuildGuildIdIndexRouteImport.update({
    id: '/guild/$guildId/',
    path: '/guild/$guildId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedGuildGuildIdApplicationsRoute =
  ProtectedGuildGuildIdApplicationsRouteImport.update({
    id: '/guild/$guildId/applications',
    path: '/guild/$guildId/applications',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedGuildGuildIdMembersUserIdRoute =
  ProtectedGuildGuildIdMembersUserIdRouteImport.update({
    id: '/guild/$guildId/members/$userId',
    path: '/guild/$guildId/members/$userId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/guild/browse': typeof ProtectedGuildBrowseRoute
  '/guild/create': typeof ProtectedGuildCreateRoute
  '/guild/': typeof ProtectedGuildIndexRoute
  '/guild/$guildId/applications': typeof ProtectedGuildGuildIdApplicationsRoute
  '/guild/$guildId/': typeof ProtectedGuildGuildIdIndexRoute
  '/guild/$guildId/members/$userId': typeof ProtectedGuildGuildIdMembersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/guild/browse': typeof ProtectedGuildBrowseRoute
  '/guild/create': typeof ProtectedGuildCreateRoute
  '/guild': typeof ProtectedGuildIndexRoute
  '/guild/$guildId/applications': typeof ProtectedGuildGuildIdApplicationsRoute
  '/guild/$guildId': typeof ProtectedGuildGuildIdIndexRoute
  '/guild/$guildId/members/$userId': typeof ProtectedGuildGuildIdMembersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/guild/browse': typeof ProtectedGuildBrowseRoute
  '/_protected/guild/create': typeof ProtectedGuildCreateRoute
  '/_protected/guild/': typeof ProtectedGuildIndexRoute
  '/_protected/guild/$guildId/applications': typeof ProtectedGuildGuildIdApplicationsRoute
  '/_protected/guild/$guildId/': typeof ProtectedGuildGuildIdIndexRoute
  '/_protected/guild/$guildId/members/$userId': typeof ProtectedGuildGuildIdMembersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/guild/browse'
    | '/guild/create'
    | '/guild/'
    | '/guild/$guildId/applications'
    | '/guild/$guildId/'
    | '/guild/$guildId/members/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/guild/browse'
    | '/guild/create'
    | '/guild'
    | '/guild/$guildId/applications'
    | '/guild/$guildId'
    | '/guild/$guildId/members/$userId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/_protected/guild/browse'
    | '/_protected/guild/create'
    | '/_protected/guild/'
    | '/_protected/guild/$guildId/applications'
    | '/_protected/guild/$guildId/'
    | '/_protected/guild/$guildId/members/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/guild/': {
      id: '/_protected/guild/'
      path: '/guild'
      fullPath: '/guild/'
      preLoaderRoute: typeof ProtectedGuildIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/guild/create': {
      id: '/_protected/guild/create'
      path: '/guild/create'
      fullPath: '/guild/create'
      preLoaderRoute: typeof ProtectedGuildCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/guild/browse': {
      id: '/_protected/guild/browse'
      path: '/guild/browse'
      fullPath: '/guild/browse'
      preLoaderRoute: typeof ProtectedGuildBrowseRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/guild/$guildId/': {
      id: '/_protected/guild/$guildId/'
      path: '/guild/$guildId'
      fullPath: '/guild/$guildId/'
      preLoaderRoute: typeof ProtectedGuildGuildIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/guild/$guildId/applications': {
      id: '/_protected/guild/$guildId/applications'
      path: '/guild/$guildId/applications'
      fullPath: '/guild/$guildId/applications'
      preLoaderRoute: typeof ProtectedGuildGuildIdApplicationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/guild/$guildId/members/$userId': {
      id: '/_protected/guild/$guildId/members/$userId'
      path: '/guild/$guildId/members/$userId'
      fullPath: '/guild/$guildId/members/$userId'
      preLoaderRoute: typeof ProtectedGuildGuildIdMembersUserIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedGuildBrowseRoute: typeof ProtectedGuildBrowseRoute
  ProtectedGuildCreateRoute: typeof ProtectedGuildCreateRoute
  ProtectedGuildIndexRoute: typeof ProtectedGuildIndexRoute
  ProtectedGuildGuildIdApplicationsRoute: typeof ProtectedGuildGuildIdApplicationsRoute
  ProtectedGuildGuildIdIndexRoute: typeof ProtectedGuildGuildIdIndexRoute
  ProtectedGuildGuildIdMembersUserIdRoute: typeof ProtectedGuildGuildIdMembersUserIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedGuildBrowseRoute: ProtectedGuildBrowseRoute,
  ProtectedGuildCreateRoute: ProtectedGuildCreateRoute,
  ProtectedGuildIndexRoute: ProtectedGuildIndexRoute,
  ProtectedGuildGuildIdApplicationsRoute:
    ProtectedGuildGuildIdApplicationsRoute,
  ProtectedGuildGuildIdIndexRoute: ProtectedGuildGuildIdIndexRoute,
  ProtectedGuildGuildIdMembersUserIdRoute:
    ProtectedGuildGuildIdMembersUserIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
